version: '3'
services:
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
    networks:
      - auth-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - auth-network

networks:
  auth-network:


volumes:
  postgres-data:
