version: '3'
services:
  # Postgres DB
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
    networks:
      - auth-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  # For caching redis
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - auth-network
    volumes:
      - cache:/var/lib/redis/data
      
  # For db manage GUI adminer
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - auth-network

# For communication within the network a common network config
networks:
  auth-network:

# To persist the data of redis & DB volume is defined
volumes:
  postgres-data:
  cache:
